### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "Thomas",
  "email": "thomas@dat255.no"
}


### Fetch all users
GET http://localhost:8080/api/users
Accept: application/json


### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "Teacher",
  "email": "teacher@dat255.no"
}


### Fetch all users
GET http://localhost:8080/api/users
Accept: application/json


### Create a poll
POST http://localhost:8080/api/polls?userid=0&question=What+class+is+this&validUntil=2025-09-12T20:30:00Z
Content-Type: application/x-www-form-urlencoded


### List all polls
GET http://localhost:8080/api/polls
Accept: application/json


### Add Vote Options
POST http://localhost:8080/api/polls/0/options?caption=DAT250
Content-Type: application/x-www-form-urlencoded


### Add Vote Options
POST http://localhost:8080/api/polls/0/options?caption=INF234
Content-Type: application/x-www-form-urlencoded


### List all polls
GET http://localhost:8080/api/polls
Accept: application/json


### Cast Vote
POST http://localhost:8080/api/vote?userId=1&pollId=0&voteOption=1
Content-Type: application/x-www-form-urlencoded


### List all polls
GET http://localhost:8080/api/polls
Accept: application/json


### Get Vote by User 2
GET http://localhost:8080/api/vote?userId=1&pollId=0
Accept: application/json


### Delete Poll
POST http://localhost:8080/api/polls/0/delete
Content-Type: application/x-www-form-urlencoded


### List all polls
GET http://localhost:8080/api/polls
Accept: application/json
